#!/usr/bin/env bash
#
# Intended to import keys easily from Github or whatever, e.g.
# $ curl https://github.com/yongjhih.keys | docker exec -i parse-server ssh-add-key
#

set -e

if [ ! -d ~/.ssh/ ]; then
    mkdir -p ~/.ssh/
fi

if [ ! -d /home/git/.ssh/ ]; then
    mkdir -p /home/git/.ssh/
    touch /home/git/.ssh/authorized_keys
    chown git:git /home/git/.ssh/authorized_keys
fi

while read line; do
  echo "$line" >> ~/.ssh/authorized_keys
  echo "$line" >> /home/git/.ssh/authorized_keys
done
